### ISSUE TITLE
Task was destroyed but it is pending

### ISSUE THREAD

**Issue by whit3rabbit** [kodycode/CoinMarketDiscordBot#37]
Get the following error when running bot:
```
python3 bot.py 
Starting bot..
CoinMarketDiscordBot is online.
Task was destroyed but it is pending!
task: <Task pending coro=<CoreFunctionality._continuous_updates() running at /[redacted]/cogs/modules/core_functionality.py:63> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10609df18>()]>>
```
Reverting back to https://github.com/kodycode/CoinMarketDiscordBot/commit/d56ade73b2c27f7c21f45f5ccdc76f6fec502a21 bot works fine.  Could possibly be related to https://github.com/kodycode/CoinMarketDiscordBot/commit/27bd7084c2ac0d3ba949217b5860ccead8f6efec.

**Comment by kodycode** [comment]
Thanks for letting me know about the commits,

For some strange reason you among others such as [this person](https://github.com/kodycode/CoinMarketDiscordBot/issues/29) have had this similar issue however I've been unable to reproduce the issue on my end as the causes of this seem pretty broad.

I'll look into this further.

**Comment by kodycode** [comment]
Code seem fine. Perhaps it could just be a hiccup or the OS you're using to run this.

Would you mind switching back to the head commit and running the bot again to see if it would work this time around? Also, if you mind, let me know what you're running the bot on?

**Comment by whit3rabbit** [comment]
Thanks for getting back so quick.

Just restarted it about 20 minutes ago and haven't run into error again (yet).

Tried it locally on OSX (High Sierra) and on a VPS running Ubuntu 17.04 and received the same error on both earlier.

Unsure what issue is TBH.  Read somewhere it could be memory or maybe low memory on my end.  I'll close the issue for now, feel free to reopen if someone else runs into problem.

**Comment by whit3rabbit** [comment]
Quick update for anyone else running into this issue.  I run the bot with pm2 now and it handles any restarts/errors.  Highly recommend it.

http://pm2.keymetrics.io/docs/usage/quick-start/

**Comment by kodycode** [comment]
I'm not familiar with pm2 but I'm curious to know, how did this help with your issue?

I'd like to pass the message down for anyone else who happens to experience the same road bump along the way.

**Comment by whit3rabbit** [comment]
Sure! pm2 will watch and reload bot on crash.  It's based one nodejs and can be installed with:

```
sudo npm install pm2@latest -g
```
So starting the bot with pm2 is as simple as running this command in CoinMarketDiscordBot folder:
```
pm2 start bot.py --interpreter /usr/bin/python3
```
Small image showing restarts/uptime.  Uptime is low because I did a git pull recently.
![image](https://user-images.githubusercontent.com/12357518/35769312-bb44cc72-08ce-11e8-9684-68dd1ac14e27.png)

You can see the number of restarts but nobody seems to notice in chat.  Works really well.

**Comment by kodycode** [comment]
Ohhh I see,

You could also setup a service for the bot using `systemd` which is a feature a part of linux to accomplish the same restart-on-failure approach, but some people may find this solution to be easier to setup.

Sad to say though I wish I could provide a better solution for these crashes. I'd rather have people not resort to these approaches to get their bot up and running.
