### ISSUE TITLE
Bug found - $addc should add coins by their symbol on COINMARKETCAP

### ISSUE THREAD

**Issue by yazeed** [kodycode/CoinMarketDiscordBot#38]
$addc supposably get the cryptocurrency or token by its symbol, yet when I use $addc ICX it adds ICON(symbol) named ICONIC instead of ICX(symbol) named ICON.

**Comment by kodycode** [comment]
Hey yazeed,

Thanks for letting me know about this. I'll have a fix up shortly for this issue.

**Comment by kodycode** [comment]
Alright, should be fixed as of https://github.com/kodycode/CoinMarketDiscordBot/commit/776f2a5804c6b8b73b21ec94af015af8a22a9f7e. Try adding ICX again with the bot now and see if it still gives you the same error.

**Comment by yazeed** [comment]
That worked, thanks a lot! 👍

**Comment by kodycode** [comment]
Awesome! If you spot any new issues feel free to make a new thread or re-open this one.
