### ISSUE TITLE
Decimal numbers for price in BTC

### ISSUE THREAD

**Issue by yazeed** [kodycode/CoinMarketDiscordBot#39]
Is there any way we can have BTC prices show correctly with all the decimals instead of the 4.7e07 format?

**Comment by kodycode** [comment]
Just modified the code to expand the price in btc display, however the live bot is going to have to wait to get it until I get home tonight. I'll update this when that happens.

**Comment by kodycode** [comment]
Alrighty changed it up. Check it out now.
