### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by rohit366** [kodycode/CoinMarketDiscordBot#40]
getting this error on one of my windows 10 machine whereas it runs on the other machine with an issue.

C:\Users\DeathStar\Desktop\Crypto Bots\CoinMarketCap Discord Bot>python bot.py
Starting bot..
ERROR:root:Bot failed to run: [Errno 10053] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [Connect call failed ('64:ff9b::6810:3b05', 443)]]
[Errno 10053] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [Connect call failed ('64:ff9b::6810:3b05', 443)]]
INFO:bot_logger:Bot is now offline.
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x043F1050>

**Comment by kodycode** [comment]
Check if your firewall is preventing this connectivity. This isn't an issue on the bot's side but rather your machine.
