### ISSUE TITLE
Actually a suggestion

### ISSUE THREAD

**Issue by dezindzer** [kodycode/CoinMarketDiscordBot#46]
I love the bot. Its easy to use, and the commands are simple.

_1._  I would love to see multiline prices, something like this 
`$s btc eth xrp `
so this would be only one post, instead of typing all three separatly

[Example](http://tinypic.com/m/k1f86v/1
)

_2_. also, a nice touch would be special commands for like top 10 coins
`$btc`
`$eth`
`$xrp`
that dont need $s before them 

Again, thanks for the great work you do. Have a good one

**Comment by kodycode** [comment]
Hey dezindzer,

Appreciate the feedback! I did actually implement multi-line prices that work in a command such as:
`$s btc,eth,bcc`, however I actually broke it a while ago and forgot to come back to fixing that so I have to thank you for reminding me about it.

As for searching up coins without typing a command string, that's something I've been thinking about for a while now and I think I'll go ahead and just put that plan into motion.

I'll update this thread once I've worked on these things.

**Comment by kodycode** [comment]
The feature should be in now, will update the bot in a bit.

Refer to https://github.com/kodycode/CoinMarketBot/wiki/Command-Page#coinmarketcommands to see some documentation it. At some point I'll remove the $search and $s commands once the majority is aware of this shortcut.

If you find any bugs, do let me know. I've tested the commands although it's not uncommon that I've missed or messed up something along the way.
