### ISSUE TITLE
suggestion for alerts

### ISSUE THREAD

**Issue by thewanderingdom** [kodycode/CoinMarketDiscordBot#47]
Just wondering if it would be possible to have alerts price set to BTC instead of fiat?
would be wonderful!

great work so far, cheers!

**Comment by kodycode** [comment]
Can do,

I'll add this idea to my list.

**Comment by kodycode** [comment]
Feature in. See `$addab` command in https://github.com/kodycode/CoinMarketBot/wiki/Command-Page#alertcommands for documentation.

If you see any problems, don't hesitate to reach out.
