### ISSUE TITLE
Using bot

### ISSUE THREAD

**Issue by TimmyAmant** [kodycode/CoinMarketDiscordBot#52]
it looks like all user can use the the bot witch i dont like, is there any way that we could make so only admin can use the bot or both if wanted. thanks

**Comment by kodycode** [comment]
Sure thing,

I'll see if I can work put out an admin-only preference some time this week.

**Comment by TimmyAmant** [comment]
Sweet thanks

**Comment by kodycode** [comment]
Just an update that it's gonna take some more time. Currently have my hands tied, but at the meantime I have most of the code written.

As a preview of what this solution is though, I plan to have the "admin(s)" (admins are decided based on a given discord role) of the discord server call upon a command such as "$admin" to enable admin-only interaction in the server.

I also plan to add more flexibility for chat interactions, so for example, you can tell the bot not to answer to 
subscriber commands unless you're an admin, and etc.

**Comment by kodycode** [comment]
Hey Tim,

I got around to creating an admin privilege feature to control what users can and can't use for commands as of https://github.com/kodycode/CoinMarketBot/pull/56. See [here to view the admin commands.](https://github.com/kodycode/CoinMarketBot/wiki/Command-Page#admincommands)

If you come across any issues, feel free to come back and re-open this ticket about it.
