### ISSUE TITLE
Unlimited alerts? Multiple alerts w/ same command

### ISSUE THREAD

**Issue by aoraion** [kodycode/CoinMarketDiscordBot#54]
I got a notification that I maxed out my alerts (10 max). Can this be increased? 

And a follow up request, it would save me alerts for the same coin to separate each price with a comma. Could you make it like this?: `$addab xlm > 0.003,0.0033,0.0038` with a max of three prices in the same alert?

**Comment by kodycode** [comment]
I can double the max amount of alerts when I get home later today. I figured 10 would be enough for someone to have, and as much as I'd like to give users the ability to have unlimited alerts, I have to draw a line to make sure nobody hogs all the resources.

As for that follow up request, that sounds like a good idea. I'll add that to the backlog however, I'm not sure when I'll be able to get cracking on it.

**Comment by aoraion** [comment]
Great! Thank you!
