### ISSUE TITLE
Coin names not matching up?

### ISSUE THREAD

**Issue by aoraion** [kodycode/CoinMarketDiscordBot#60]
First off, thanks for the admin settings ;)
I tried to create an alert for YOYO but it kept saying that coin wasn't found. I know that if I wanted to create an alert for POET it would find it and recognize it as Po.et. Can the trading names of coins be added to the database?

**Comment by kodycode** [comment]
Hey aoraion,

Happy to hear the admin settings are being useful!

All coins that can be found through the bot are based on whatever coins can be found on coinmarketcap. That being said, if the coin can't be found, then it's probably not registered to coinmarketcap.

I've never heard of a cryptocurrency under the acronym YOYO, do you mean YOYOW?

Also, by trading name, do you mean the acronym for that cryptocurrency? If you want to create an alert for POET, you can simply use the acronym (POE) to create the alert for Po.et. Does that answer your question?

**Comment by aoraion** [comment]
YOYO is the trading ticker for YOYOW, yes, but when I typed in YOYO it
wouldn't recognize it. It would be more useful to use tickers instead of
proper names of companies. Can this be fixed?

Thanks!

**Comment by kodycode** [comment]
Unfortunately, there’s not much I can do on my end. The ticker YOYOW decided to register their currency remains as YOYOW, for their full name to look up or their acronym.
