### ISSUE TITLE
Change alert number to plain text?

### ISSUE THREAD

**Issue by aoraion** [kodycode/CoinMarketDiscordBot#63]
![img_3561](https://user-images.githubusercontent.com/30146751/38401206-61c4e550-398f-11e8-9cf1-90cd690cacc3.jpg)
I got a pushed alert from Discord, which is great, except the formatting is a bit messy, but formatting isn't my main issue. On Discord it looks formatted for Discord with markdown, but the number is formatted to a mathematical number instead of a plain text number, or the way it was entered in, e.g., `$addab yoyow > .000012`. Is there a way to keep the number formatted in the way it was entered?

And piggybacking on the pushed alerts, is there a way to change the format of the alert for push notifications? It's not a big of deal as the number formatting, so if it needs to stay the same, then that's fine.

**Comment by kodycode** [comment]
Thanks for bringing this up, I didn't realize the bot displayed numbers in exponential forms in the alert feature. I definitely would want it to be display the full number instead.

I'll make the change for that either late tonight or tomorrow.

As for the markdown syntax showing in the push notification, I'm afraid that's just the way it's going to be. However, assuming that you're hosting the bot yourself, you can change the formatting in the function `alert_user` which exists in `alert_functionality.py`.

**Comment by kodycode** [comment]
Fixed as of https://github.com/kodycode/CoinMarketBot/pull/64

See notes on this from https://github.com/kodycode/CoinMarketBot/wiki/Updates
