### ISSUE TITLE
Add more sub interval options

### ISSUE THREAD

**Issue by kodycode** [kodycode/CoinMarketDiscordBot#68]

**Comment by rohit366** [comment]
Hi @kodycode I have added these in my local files as follows 
Possible rate inputs currently are:
"default" - posts every 5 minutes
"ten" - post every 10 minutes
"quar" - post every 15 minutes
"half" - posts at every half-hour mark
"hourly" - posts at every hour mark

would you like me to add to your code. I am new to github so ill try to added them to my fork.

**Comment by kodycode** [comment]
Hey Rohit,

I appreciate the help. Make a PR so I can check the code out.

**Comment by rohit366** [comment]
I tried to but getting an error of having no access to send the pull request.

**Comment by rohit366** [comment]
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

**Comment by kodycode** [comment]
How’re you trying to create this request? You shouldn’t need to have permission to create one. Your branch should be forked and your code on that forked branch as well, and from there you can just go on GitHub to create the branch.

**Comment by kodycode** [comment]
Done for now..future re-work may come for this setting.
