### ISSUE TITLE
Display coin icon in the Discord embed

### ISSUE THREAD

**Issue by cryptochrome** [kodycode/CoinMarketDiscordBot#72]
Hi,

I would love to see an enhancement to the bot that would display the coin/token icon in the Discord embed when pulling CMC data. Like so:

<img width="314" alt="price-check - discord 2018-05-13 15-58-14" src="https://user-images.githubusercontent.com/4440762/39968017-8af38bc6-56c6-11e8-8d6c-d74715612f6f.png">

(this is from a different bot)

It would look much nicer. Asthetics count :)

**Comment by kodycode** [comment]
Hey chrome,

I'd definitely like to add pics/icons but that's going to be held off for the time being. The coinmarketcap API doesn't supply you with the image icons, though I'm aware of the API this other bot uses to get this information. At some point soon, I do plan on switching over to this other API, but that's going to have to wait a bit as I'd like to get some other features in beforehand.

For now though I'll add this to my backlog.

**Comment by cryptochrome** [comment]
No rush. Appreciate it that you are considering to add it :)

**Comment by kodycode** [comment]
Hey @cryptochrome, it's been a while but I threw in this feature so it should be all set. The bot is currently down for the time-being but I plan to bring it back up tonight once I address certain things about the new updates done for the bot.
