### ISSUE TITLE
Link back to CMC website

### ISSUE THREAD

**Issue by cryptochrome** [kodycode/CoinMarketDiscordBot#73]
It would be nice if the Discord embed had a link back to CMC, so that when you click on the link in the embed, a web browser opens and goes to the coin's/token's page on CMC.

**Comment by cryptochrome** [comment]
Like this:

<img width="314" alt="price-check - discord 2018-05-13 15-58-14" src="https://user-images.githubusercontent.com/4440762/39968046-f8e372b8-56c6-11e8-8711-b566e18444c5.png">

**Comment by kodycode** [comment]
Keeping this in the backlog.

**Comment by kodycode** [comment]
Finished as of https://github.com/kodycode/CoinMarketBot/commit/81144e4097d7cce6134f05f7c952570bceb9d770.
