### ISSUE TITLE
Coin Ranking

### ISSUE THREAD

**Issue by cryptochrome** [kodycode/CoinMarketDiscordBot#74]
It would be nice to have CMC ranking right in the bot. For example:

`$top 10` - display top 10 coins by market cap
`$top 5 gain` - display top 5 gainers by price increase
`$top 5 loser` - display top 5 losers by price decrease 

In addition to that, the coin's rank could be displayed in the Discord embed when pulling data for the coin, like so:

<img width="314" alt="price-check - discord 2018-05-13 15-58-14" src="https://user-images.githubusercontent.com/4440762/39968076-77e3d6d4-56c7-11e8-87a2-de2210475392.png">

**Comment by kodycode** [comment]
Not a bad idea. I'll add this to my list.

To be clear, when you say gain/loser in relation to price increase/decrease, do you mean the price percentage that's increasing/decreasing?

**Comment by cryptochrome** [comment]
Yep, the percentage. Basically the same thing you would get when you sort coins by "Change (24h)" on CMC:

<img width="236" alt="cryptocurrency market capitalizations coinmarketcap 2018-05-13 18-31-01" src="https://user-images.githubusercontent.com/4440762/39969430-d441d908-56db-11e8-9190-e43f9a758bb2.png">

**Comment by kodycode** [comment]
Alright, sounds do-able.

To note, the rank is already included when you search up the coin through the bot. It's the number you see on the first line of the result looking something like `#1. Bitcoin`.

**Comment by ghost** [comment]
Upvote for this one :-) Good idea!

**Comment by kodycode** [comment]
Added as of https://github.com/kodycode/CoinMarketBot/commit/8c908b9997ebe3b3923cc4641c1f1826f2c2c9b9. See bot help or [Command Page](https://github.com/kodycode/CoinMarketBot/wiki/Command-Page) for instructions. I limited to just displaying 5 cryptocurrencies to not bombard the chatroom so much.
