### ISSUE TITLE
can't install the bot

### ISSUE THREAD

**Issue by Clemiax** [kodycode/CoinMarketDiscordBot#75]
Hi, i can install the bot with pip.

i have this response when i enter ``pip install -r requirements.txt`` :

``
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
``

**Comment by kodycode** [comment]
Hey Clem,

That's an issue not related to my bot. It appears there's some problems with one of the recent versions of pip. You're answer may rely here: 

https://stackoverflow.com/questions/28210269/importerror-cannot-import-name-main-when-running-pip-version-command-in-windo

Or anywhere else. You can also try downgrading your pip version to 9.0.3, but that's up to you.
