### ISSUE TITLE
Coinmarketcal: daily overview

### ISSUE THREAD

**Issue by ghost** [kodycode/CoinMarketDiscordBot#79]
Hi, 

Thanks for fixing our previous issue so quickly.
Would it be possible to have the bot post an overview of todays's, tomorrow's and perhaps weekly events?
This in some kind of dropdown so one doesn't get several pages spammed?

Thanks, 

Brando

**Comment by kodycode** [comment]
Can do,

Though to make sure I'm understanding this correctly, what do you have in mind when you say dropdown? Pages spammed meaning you don't want to have to continuously type in the next event number correct?

**Comment by kodycode** [comment]
Dropping coinmarketcal feature unfortunately. See https://github.com/kodycode/CoinMarketBot/issues/84#issuecomment-520242581 for reason.
