### ISSUE TITLE
Where to find coinmarketcal id and secret? 

### ISSUE THREAD

**Issue by dylie** [kodycode/CoinMarketDiscordBot#83]
Where can you find this? I can only find the API key it gives you.

Kind regards, dylan

**Comment by dylie** [comment]
> Where can you find this? I can only find the API key it gives you.
> 
> Kind regards, dylan

update, they changing to https://coinmarketcal.com/en/developer/dashboard there's no option for this there.

**Comment by kodycode** [comment]
Thanks for letting me know, I'll have this updated soon.

**Comment by dylie** [comment]
Any clue when you can find some time to have a fix? Not pushing, just really wanna use this code 🥇

**Comment by kodycode** [comment]
Oh shoot, I didn't realize it prevented the bot from going up. I'll try to work something out today..

**Comment by kodycode** [comment]
For now, I'm going to disable coinmarketcal features for the time being. I'll have to find some time later to look through the new API, but for now the bot should work for everything else.

Additionally, install my coinmarketcap wrapper after installing the bot dependencies as well. The original creator of the wrapper hasn't updated the main wrapper in a while, so I've updated it myself to get all the cryptocurrency data.

https://github.com/kodycode/coinmarketcap

**Comment by dylie** [comment]
Alright! Thanks! Can't wait to try it out.

**Comment by dylie** [comment]
> Alright! Thanks! Can't wait to try it out.
> 
> EDIT: just tested it after installing with your coinmarketcap edits, gives me a failed to update market and failed to load cryptocorrency acronyms error? Any idea's?

error is: [03/24/2019 12:55:04 PM](bot.py) - INFO - Starting bot..
[03/24/2019 12:55:43 PM](coin_market.py) - ERROR - Failed to retrieve data - Connection error: Invalid URL '87086470-aaa5-4c75-9c99-9dfb1a8c2d45global/': No schema supplied. Perhaps you meant http://87086470-aaa5-4c75-9c99-9dfb1a8c2d45global/?
[03/24/2019 12:55:43 PM](core_functionality.py) - ERROR - Exception: Failed to fetch all cryptocurrencies: `listings() got an unexpected keyword argument 'limit'`
[03/24/2019 12:55:43 PM](core_functionality.py) - ERROR - Exception: Market list was not loaded.
[03/24/2019 12:55:43 PM](core_functionality.py) - INFO - Bot is online

**Comment by dylie** [comment]
al good!

**Comment by kodycode** [comment]
Good to hear! Let me know if there are any other problems that occur.
