### ISSUE TITLE
When will $cb work again?

### ISSUE THREAD

**Issue by dylie** [kodycode/CoinMarketDiscordBot#84]
Any updates on this?

**Comment by kodycode** [comment]
Hi, sorry for the late reply.

I finally got around to reaching out to the coinmarketcal team to learn more about their new API plans and I've decided that I'm dropping the coinmarketcal feature from the bot. Without funding, the free tier service doesn't provide great features to make the implementation worthwhile for the bot. Nevertheless, I'm open to any PR's if someone is willing to go ahead and make an implementation for it, but I'm not going to bother with it.
